export type {
  EncounterStatus,
  EncounterType,
  ClinicalEncounter,
  CreateEncounterDto,
  UpdateEncounterDto,
  TranscribeAudioDto,
  TranscriptionResponseDto,
  TranscriptionSegment,
  UpdateTranscriptDto,
  ClinicalVitalSign,
  ClinicalExtraction,
  UpdateExtractionDto,
  SoapNote,
  UpdateSoapNoteDto,
  PrescriptionStatus,
  PrescriptionItem,
  UpdatePrescriptionsDto,
  DiagnosisType,
  DiagnosisCertainty,
  DiagnosisStatus,
  DiagnosisItem,
  ClinicalImpression,
  UpdateClinicalImpressionDto,
} from '@org/models';


